version: '3'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gateway_api
    hostname: gateway_api
    volumes:
      - .:/usr/apps/gateway
    command: npm run start:dev
    ports: 
      - '3001:3001'
      - '9230:9230'
    networks:
      - host

networks:
  host:
    driver: bridge
