version: '3'

services:
  postgres:
    image: postgres:14.1
    container_name: customers_db
    hostname: customers_db
    env_file:
    - .env
    volumes:
      - pgdata:/var/lib/postgressql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=${HOST_PG}
      - POSTGRES_USER=${USERNAME_PG}
      - POSTGRES_PASSWORD=${PASSWORD_PG}
      - POSTGRES_DB=${DATABASE_PG}
    networks:
      - customers
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customers_api
    hostname: customers_api
    volumes:
      - .:/usr/apps/customers
    command: npm run start:dev
    ports: 
      - '3001:3001'
      - '9229:9229'
    depends_on:
      - postgres
    networks:
      - customers

volumes:
  pgdata:  

networks:
  customers:
    driver: bridge